name: Fetch API Data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # This runs every hour
  push:
    branches:
      - test_notification

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        working-directory: /monex_server
        run: |
          cd push_notification
          python fetch_api_data.py
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONEX_APP_F86C7 }}
